library(sp)
library(shapefiles)
library(maptools)
library(CARBayesdata)
library(rgdal)
library(spdep)
library(classInt)
library(RColorBrewer)
setwd("~/4th Year/project/data/Data/CCG_shapefile")
shape <- readOGR('.', 'CCG_BSC Feb2013  (clipcoast 200m)')
neib <- poly2nb(shape)
coords <- coordinates(shape)
plot(shape)
plot(neib, coords, col="blue", add=TRUE)
load("~/4th Year/project/data/Data/expected_data.Rda")
cases = asthma_expected_i['E']
cases_data <- as.data.frame(cases)
class <- classIntervals(cases_data$E, 8, style="quantile")
plotclr <- brewer.pal(8,"YlOrRd")
colcode <- findColours(class, plotclr)
plot(shape, col=colcode)